/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminWalletsRouteImport } from './routes/_admin/wallets'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminRolesRouteImport } from './routes/_admin/roles'
import { Route as AdminP2pRouteImport } from './routes/_admin/p2p'
import { Route as AdminModulesRouteImport } from './routes/_admin/modules'
import { Route as AdminMarketsRouteImport } from './routes/_admin/markets'
import { Route as AdminMarketHistoryRouteImport } from './routes/_admin/market-history'
import { Route as AdminMarketCategoriesRouteImport } from './routes/_admin/market-categories'
import { Route as AdminLoadTestRouteImport } from './routes/_admin/load-test'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminBannersRouteImport } from './routes/_admin/banners'
import { Route as AdminAccessCodesRouteImport } from './routes/_admin/access-codes'
import { Route as AdminSettingsTelegramRouteImport } from './routes/_admin/settings.telegram'
import { Route as AdminSettingsSecurityRouteImport } from './routes/_admin/settings.security'
import { Route as AdminSettingsProfileRouteImport } from './routes/_admin/settings.profile'
import { Route as AdminSettingsPaymentTypesRouteImport } from './routes/_admin/settings.payment-types'
import { Route as AdminSettingsPaymentRouteImport } from './routes/_admin/settings.payment'
import { Route as AdminSettingsCryptoWalletRouteImport } from './routes/_admin/settings.crypto-wallet'
import { Route as AdminP2pP2pIdRouteImport } from './routes/_admin/p2p_.$p2pId'
import { Route as AdminP2pApplicationsApplicationIdRouteImport } from './routes/_admin/p2p_.applications.$applicationId'
import { Route as AdminMarketsMarketIdEditRouteImport } from './routes/_admin/markets_.$marketId.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminP2pRoute = AdminP2pRouteImport.update({
  id: '/p2p',
  path: '/p2p',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketsRoute = AdminMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketHistoryRoute = AdminMarketHistoryRouteImport.update({
  id: '/market-history',
  path: '/market-history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketCategoriesRoute = AdminMarketCategoriesRouteImport.update({
  id: '/market-categories',
  path: '/market-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoadTestRoute = AdminLoadTestRouteImport.update({
  id: '/load-test',
  path: '/load-test',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessCodesRoute = AdminAccessCodesRouteImport.update({
  id: '/access-codes',
  path: '/access-codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsTelegramRoute = AdminSettingsTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsSecurityRoute = AdminSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsProfileRoute = AdminSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsPaymentTypesRoute =
  AdminSettingsPaymentTypesRouteImport.update({
    id: '/payment-types',
    path: '/payment-types',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsPaymentRoute = AdminSettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsCryptoWalletRoute =
  AdminSettingsCryptoWalletRouteImport.update({
    id: '/crypto-wallet',
    path: '/crypto-wallet',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminP2pP2pIdRoute = AdminP2pP2pIdRouteImport.update({
  id: '/p2p_/$p2pId',
  path: '/p2p/$p2pId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminP2pApplicationsApplicationIdRoute =
  AdminP2pApplicationsApplicationIdRouteImport.update({
    id: '/p2p_/applications/$applicationId',
    path: '/p2p/applications/$applicationId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketsMarketIdEditRoute =
  AdminMarketsMarketIdEditRouteImport.update({
    id: '/markets_/$marketId/edit',
    path: '/markets/$marketId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/access-codes': typeof AdminAccessCodesRoute
  '/banners': typeof AdminBannersRoute
  '/dashboard': typeof AdminDashboardRoute
  '/load-test': typeof AdminLoadTestRoute
  '/market-categories': typeof AdminMarketCategoriesRoute
  '/market-history': typeof AdminMarketHistoryRoute
  '/markets': typeof AdminMarketsRoute
  '/modules': typeof AdminModulesRoute
  '/p2p': typeof AdminP2pRoute
  '/roles': typeof AdminRolesRoute
  '/settings': typeof AdminSettingsRouteWithChildren
  '/users': typeof AdminUsersRoute
  '/wallets': typeof AdminWalletsRoute
  '/p2p/$p2pId': typeof AdminP2pP2pIdRoute
  '/settings/crypto-wallet': typeof AdminSettingsCryptoWalletRoute
  '/settings/payment': typeof AdminSettingsPaymentRoute
  '/settings/payment-types': typeof AdminSettingsPaymentTypesRoute
  '/settings/profile': typeof AdminSettingsProfileRoute
  '/settings/security': typeof AdminSettingsSecurityRoute
  '/settings/telegram': typeof AdminSettingsTelegramRoute
  '/markets/$marketId/edit': typeof AdminMarketsMarketIdEditRoute
  '/p2p/applications/$applicationId': typeof AdminP2pApplicationsApplicationIdRoute
}
export interface FileRoutesByTo {
  '/access-codes': typeof AdminAccessCodesRoute
  '/banners': typeof AdminBannersRoute
  '/dashboard': typeof AdminDashboardRoute
  '/load-test': typeof AdminLoadTestRoute
  '/market-categories': typeof AdminMarketCategoriesRoute
  '/market-history': typeof AdminMarketHistoryRoute
  '/markets': typeof AdminMarketsRoute
  '/modules': typeof AdminModulesRoute
  '/p2p': typeof AdminP2pRoute
  '/roles': typeof AdminRolesRoute
  '/settings': typeof AdminSettingsRouteWithChildren
  '/users': typeof AdminUsersRoute
  '/wallets': typeof AdminWalletsRoute
  '/': typeof AdminIndexRoute
  '/p2p/$p2pId': typeof AdminP2pP2pIdRoute
  '/settings/crypto-wallet': typeof AdminSettingsCryptoWalletRoute
  '/settings/payment': typeof AdminSettingsPaymentRoute
  '/settings/payment-types': typeof AdminSettingsPaymentTypesRoute
  '/settings/profile': typeof AdminSettingsProfileRoute
  '/settings/security': typeof AdminSettingsSecurityRoute
  '/settings/telegram': typeof AdminSettingsTelegramRoute
  '/markets/$marketId/edit': typeof AdminMarketsMarketIdEditRoute
  '/p2p/applications/$applicationId': typeof AdminP2pApplicationsApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/access-codes': typeof AdminAccessCodesRoute
  '/_admin/banners': typeof AdminBannersRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/load-test': typeof AdminLoadTestRoute
  '/_admin/market-categories': typeof AdminMarketCategoriesRoute
  '/_admin/market-history': typeof AdminMarketHistoryRoute
  '/_admin/markets': typeof AdminMarketsRoute
  '/_admin/modules': typeof AdminModulesRoute
  '/_admin/p2p': typeof AdminP2pRoute
  '/_admin/roles': typeof AdminRolesRoute
  '/_admin/settings': typeof AdminSettingsRouteWithChildren
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/wallets': typeof AdminWalletsRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/p2p_/$p2pId': typeof AdminP2pP2pIdRoute
  '/_admin/settings/crypto-wallet': typeof AdminSettingsCryptoWalletRoute
  '/_admin/settings/payment': typeof AdminSettingsPaymentRoute
  '/_admin/settings/payment-types': typeof AdminSettingsPaymentTypesRoute
  '/_admin/settings/profile': typeof AdminSettingsProfileRoute
  '/_admin/settings/security': typeof AdminSettingsSecurityRoute
  '/_admin/settings/telegram': typeof AdminSettingsTelegramRoute
  '/_admin/markets_/$marketId/edit': typeof AdminMarketsMarketIdEditRoute
  '/_admin/p2p_/applications/$applicationId': typeof AdminP2pApplicationsApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-codes'
    | '/banners'
    | '/dashboard'
    | '/load-test'
    | '/market-categories'
    | '/market-history'
    | '/markets'
    | '/modules'
    | '/p2p'
    | '/roles'
    | '/settings'
    | '/users'
    | '/wallets'
    | '/p2p/$p2pId'
    | '/settings/crypto-wallet'
    | '/settings/payment'
    | '/settings/payment-types'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/telegram'
    | '/markets/$marketId/edit'
    | '/p2p/applications/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-codes'
    | '/banners'
    | '/dashboard'
    | '/load-test'
    | '/market-categories'
    | '/market-history'
    | '/markets'
    | '/modules'
    | '/p2p'
    | '/roles'
    | '/settings'
    | '/users'
    | '/wallets'
    | '/'
    | '/p2p/$p2pId'
    | '/settings/crypto-wallet'
    | '/settings/payment'
    | '/settings/payment-types'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/telegram'
    | '/markets/$marketId/edit'
    | '/p2p/applications/$applicationId'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/access-codes'
    | '/_admin/banners'
    | '/_admin/dashboard'
    | '/_admin/load-test'
    | '/_admin/market-categories'
    | '/_admin/market-history'
    | '/_admin/markets'
    | '/_admin/modules'
    | '/_admin/p2p'
    | '/_admin/roles'
    | '/_admin/settings'
    | '/_admin/users'
    | '/_admin/wallets'
    | '/_admin/'
    | '/_admin/p2p_/$p2pId'
    | '/_admin/settings/crypto-wallet'
    | '/_admin/settings/payment'
    | '/_admin/settings/payment-types'
    | '/_admin/settings/profile'
    | '/_admin/settings/security'
    | '/_admin/settings/telegram'
    | '/_admin/markets_/$marketId/edit'
    | '/_admin/p2p_/applications/$applicationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/wallets': {
      id: '/_admin/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles': {
      id: '/_admin/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/p2p': {
      id: '/_admin/p2p'
      path: '/p2p'
      fullPath: '/p2p'
      preLoaderRoute: typeof AdminP2pRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/modules': {
      id: '/_admin/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/markets': {
      id: '/_admin/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AdminMarketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/market-history': {
      id: '/_admin/market-history'
      path: '/market-history'
      fullPath: '/market-history'
      preLoaderRoute: typeof AdminMarketHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/market-categories': {
      id: '/_admin/market-categories'
      path: '/market-categories'
      fullPath: '/market-categories'
      preLoaderRoute: typeof AdminMarketCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/load-test': {
      id: '/_admin/load-test'
      path: '/load-test'
      fullPath: '/load-test'
      preLoaderRoute: typeof AdminLoadTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/banners': {
      id: '/_admin/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/access-codes': {
      id: '/_admin/access-codes'
      path: '/access-codes'
      fullPath: '/access-codes'
      preLoaderRoute: typeof AdminAccessCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/telegram': {
      id: '/_admin/settings/telegram'
      path: '/telegram'
      fullPath: '/settings/telegram'
      preLoaderRoute: typeof AdminSettingsTelegramRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/settings/security': {
      id: '/_admin/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AdminSettingsSecurityRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/settings/profile': {
      id: '/_admin/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AdminSettingsProfileRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/settings/payment-types': {
      id: '/_admin/settings/payment-types'
      path: '/payment-types'
      fullPath: '/settings/payment-types'
      preLoaderRoute: typeof AdminSettingsPaymentTypesRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/settings/payment': {
      id: '/_admin/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof AdminSettingsPaymentRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/settings/crypto-wallet': {
      id: '/_admin/settings/crypto-wallet'
      path: '/crypto-wallet'
      fullPath: '/settings/crypto-wallet'
      preLoaderRoute: typeof AdminSettingsCryptoWalletRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/p2p_/$p2pId': {
      id: '/_admin/p2p_/$p2pId'
      path: '/p2p/$p2pId'
      fullPath: '/p2p/$p2pId'
      preLoaderRoute: typeof AdminP2pP2pIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/p2p_/applications/$applicationId': {
      id: '/_admin/p2p_/applications/$applicationId'
      path: '/p2p/applications/$applicationId'
      fullPath: '/p2p/applications/$applicationId'
      preLoaderRoute: typeof AdminP2pApplicationsApplicationIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/markets_/$marketId/edit': {
      id: '/_admin/markets_/$marketId/edit'
      path: '/markets/$marketId/edit'
      fullPath: '/markets/$marketId/edit'
      preLoaderRoute: typeof AdminMarketsMarketIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminSettingsRouteChildren {
  AdminSettingsCryptoWalletRoute: typeof AdminSettingsCryptoWalletRoute
  AdminSettingsPaymentRoute: typeof AdminSettingsPaymentRoute
  AdminSettingsPaymentTypesRoute: typeof AdminSettingsPaymentTypesRoute
  AdminSettingsProfileRoute: typeof AdminSettingsProfileRoute
  AdminSettingsSecurityRoute: typeof AdminSettingsSecurityRoute
  AdminSettingsTelegramRoute: typeof AdminSettingsTelegramRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsCryptoWalletRoute: AdminSettingsCryptoWalletRoute,
  AdminSettingsPaymentRoute: AdminSettingsPaymentRoute,
  AdminSettingsPaymentTypesRoute: AdminSettingsPaymentTypesRoute,
  AdminSettingsProfileRoute: AdminSettingsProfileRoute,
  AdminSettingsSecurityRoute: AdminSettingsSecurityRoute,
  AdminSettingsTelegramRoute: AdminSettingsTelegramRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminRouteChildren {
  AdminAccessCodesRoute: typeof AdminAccessCodesRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoadTestRoute: typeof AdminLoadTestRoute
  AdminMarketCategoriesRoute: typeof AdminMarketCategoriesRoute
  AdminMarketHistoryRoute: typeof AdminMarketHistoryRoute
  AdminMarketsRoute: typeof AdminMarketsRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminP2pRoute: typeof AdminP2pRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminP2pP2pIdRoute: typeof AdminP2pP2pIdRoute
  AdminMarketsMarketIdEditRoute: typeof AdminMarketsMarketIdEditRoute
  AdminP2pApplicationsApplicationIdRoute: typeof AdminP2pApplicationsApplicationIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessCodesRoute: AdminAccessCodesRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoadTestRoute: AdminLoadTestRoute,
  AdminMarketCategoriesRoute: AdminMarketCategoriesRoute,
  AdminMarketHistoryRoute: AdminMarketHistoryRoute,
  AdminMarketsRoute: AdminMarketsRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminP2pRoute: AdminP2pRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminP2pP2pIdRoute: AdminP2pP2pIdRoute,
  AdminMarketsMarketIdEditRoute: AdminMarketsMarketIdEditRoute,
  AdminP2pApplicationsApplicationIdRoute:
    AdminP2pApplicationsApplicationIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
